// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Newspaper.Models
{
    [Table("Article")]
    public partial class Article
    {
        [Key]
        public int Art_ID { get; set; }
        [Unicode(false)]
        public string Text { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        public bool IsActive { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Category_Name { get; set; }
        public int WriterID { get; set; }

        [ForeignKey("Category_Name")]
        [InverseProperty("Articles")]
        public virtual Category Category_NameNavigation { get; set; }
        [ForeignKey("WriterID")]
        [InverseProperty("Articles")]
        public virtual User Writer { get; set; }
    }
}